### ISSUE TITLE
前辈您好，我想咨询下PA3最后的仙剑奇侠转的数据文件怎么获取？

### ISSUE THREAD

**Issue by DuskwatcherLT** [NJU-ProjectN/ics-pa-gitbook#1]
前辈您好：
我在做PA实验第三部分时，最后需要仙剑奇侠传的数据文件进行测试。那个实验的指引说 从课程网站上下载仙剑奇侠传的数据文件, 并放到navy-apps/fsimg/share/games/pal/目录下。
我不是南京大学的学生，这个课程网站要在哪里获取哈。
十分感谢前辈有时间阅读我的提问，谢谢。

**Comment by jiangyy** [comment]
这个涉及到版权问题，所以只在小范围发布，供研究和测试用。

**Comment by Donald-xue** [comment]
> 前辈您好： 我在做PA实验第三部分时，最后需要仙剑奇侠传的数据文件进行测试。那个实验的指引说 从课程网站上下载仙剑奇侠传的数据文件, 并放到navy-apps/fsimg/share/games/pal/目录下。 我不是南京大学的学生，这个课程网站要在哪里获取哈。 十分感谢前辈有时间阅读我的提问，谢谢。

你好，我想问一下您找到了仙剑奇侠传的数据文件么？

**Comment by The-ch0sen0ne** [comment]
> > 前辈您好： 我在做PA实验第三部分时，最后需要仙剑奇侠传的数据文件进行测试。那个实验的指引说 从课程网站上下载仙剑奇侠传的数据文件, 并放到navy-apps/fsimg/share/games/pal/目录下。 我不是南京大学的学生，这个课程网站要在哪里获取哈。 十分感谢前辈有时间阅读我的提问，谢谢。
> 
> 你好，我想问一下您找到了仙剑奇侠传的数据文件么？

https://blog.csdn.net/flx413/article/details/82533736

**Comment by jundao17** [comment]
仙剑官网购买还能拿到的

**Comment by Donald-xue** [comment]
我也是从另一个师兄那里拿到的，你需要的话我发给你，可以加我微信1401568751发自我的平板-------- 原始邮件 --------发件人： jundao17 ***@***.***>日期： 2023年7月25日周二 下午2:44收件人： NJU-ProjectN/ics-pa-gitbook ***@***.***>抄送： Donald-xue ***@***.***>, Comment ***@***.***>主    题： Re: [NJU-ProjectN/ics-pa-gitbook] 前辈您好，我想咨询下PA3最后的仙剑奇侠转的数据文件怎么获取？ (#1)
仙剑官网购买还能拿到的

**Comment by GuoYS0010** [comment]
https://www点52pojie点cn/thread-1011448-1-1.html这里有

**Comment by ctoLuu** [comment]
> [https://www点52pojie点cn/thread-1011448-1-1.html这里有](https://www%E7%82%B952pojie%E7%82%B9cn/thread-1011448-1-1.html%E8%BF%99%E9%87%8C%E6%9C%89)

应该用的是哪一个啊，我跑了都报错，debug出来应该就是文件加载的问题

**Comment by BoogieEnzo** [comment]
求下载链接

**Comment by taotao419** [comment]
上面链接亲测可用, 请下载仙剑奇侠传1dos版.rar文件. 解压后注意原版文件名一般是大写的，而开源Linux版需要全部小写的文件。需要一一改过来。

**Comment by 2062423268** [comment]
> 上面链接亲测可用, 请下载仙剑奇侠传1dos版.rar文件. 解压后注意原版文件名一般是大写的，而开源Linux版需要全部小写的文件。需要一一改过来。

@taotao419 你好，请问能告知具体是哪些文件要放进data里面吗？谢谢

**Comment by taotao419** [comment]
@2062423268 是如下这些文件, 复制到 pal/repo/data 文件夹
<img width="294" height="982" alt="Image" src="https://github.com/user-attachments/assets/a85013c3-5697-4d7d-a2cf-121214e344de" />
