### ISSUE TITLE
1.6 debug_hook 已经在 58f009646 被删除

### ISSUE THREAD

**Issue by wlbksy** [NJU-ProjectN/ics-pa-gitbook#10]
![image](https://user-images.githubusercontent.com/2433806/137159817-88ce32e8-7919-4555-965d-09cb684b94d5.png)

![image](https://user-images.githubusercontent.com/2433806/137159921-c2ab3d6e-69de-49e2-837d-23412602779c.png)

![image](https://user-images.githubusercontent.com/2433806/137159599-429d2bcf-f3ec-4c86-ad83-be43e20d60d3.png)

**Comment by sashimi-yzh** [comment]
感谢指出, 已修复.
