### ISSUE TITLE
installing llvm of pa0

### ISSUE THREAD

**Issue by funny1dog** [NJU-ProjectN/ics-pa-gitbook#12]
安装llvm的命令是不是有些问题：apt-get install llvm               # llvm project, which contains libraries used later
我在ubuntu21下面运行上面的命令后安装了llvm-6，在之后的make出现许多的错误
llvm/Support/TargetRegistry.h: No such file or directory

在另一个issue里面告知了可以安装llvm-11来解决，那为什么不直接把上面的apt-get install llvm 替换为apt-get install llvm-11呢？
modify nemu/src/utils/filelist.mk to use llvm-config-11 instead of llvm-config
谢谢。

**Comment by sashimi-yzh** [comment]
有人的环境里面没有llvm-11(例如 https://github.com/NJU-ProjectN/ics-pa/issues/8), 所以最好是不指定版本

我说明一下最低版本是11
