### ISSUE TITLE
关于讲义 3.2 节没有及时更新的一处路径

### ISSUE THREAD

**Issue by good-circle** [NJU-ProjectN/ics-pa-gitbook#13]
在 PA3.2 - 穿越时空的旅程 - 将上下文管理抽象成CTE - 设置异常入口地址中，讲义中描述的是：这最终会调用位于 `abstract-machine/am/src/nemu/isa/$ISA/cte.c` 中的 `cte_init()` 函数；但在 ics2021 及以后的版本中，该路径应该为 `abstract-machine/am/src/$ISA/nemu/cte.c` 。

麻烦老师啦 ~

**Comment by sashimi-yzh** [comment]
已修复, 感谢指出!
