### ISSUE TITLE
PA3.3中的仙剑奇侠传配置文件文件能否提供一下

### ISSUE THREAD

**Issue by junjie1475** [NJU-ProjectN/ics-pa-gitbook#14]
这个应该不违反版权吧

**Comment by sashimi-yzh** [comment]
讲义有写

**Comment by junjie1475** [comment]
> 讲义有写

emm我的意思是你们发布在课程群的公告中的配置文件，主要是其他文件好找但是配置文件因环境而变化 配置文件写错了就很麻烦

**Comment by sashimi-yzh** [comment]
哦哦, 我先贴一个可用的吧, 晚点再放到讲义里面, 感觉可以简化一下:
```
KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=0
UseSurroundOPL=0
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=0
EnableGLSL=0
EnableHDR=0
SurroundOPLOffset=384
LogLevel=5
AudioDevice=-1
AudioBufferSize=2048
OPLSampleRate=11025
ResampleQuality=0
SampleRate=11025
MusicVolume=100
SoundVolume=100
WindowHeight=200
WindowWidth=320
TextureHeight=200
TextureWidth=320
CD=NONE
Music=RIX
OPLCore=DBINT
OPLChip=OPL2
```

**Comment by junjie1475** [comment]
> 哦哦, 我先贴一个可用的吧, 晚点再放到讲义里面, 感觉可以简化一下:
> 
> ```
> KeepAspectRatio=1
> FullScreen=0
> LaunchSetting=0
> Stereo=0
> UseSurroundOPL=0
> EnableKeyRepeat=0
> UseTouchOverlay=0
> EnableAviPlay=0
> EnableGLSL=0
> EnableHDR=0
> SurroundOPLOffset=384
> LogLevel=5
> AudioDevice=-1
> AudioBufferSize=2048
> OPLSampleRate=11025
> ResampleQuality=0
> SampleRate=11025
> MusicVolume=100
> SoundVolume=100
> WindowHeight=200
> WindowWidth=320
> TextureHeight=200
> TextureWidth=320
> CD=NONE
> Music=RIX
> OPLCore=DBINT
> OPLChip=OPL2
> ```
非常感谢!

**Comment by sashimi-yzh** [comment]
我这边试了一下, 发现简化为如下4行仍然可以工作, 不知道你是否方便测试一下? @junjie1475 
```
OPLSampleRate=11025
SampleRate=11025
WindowHeight=200
WindowWidth=320
```

**Comment by junjie1475** [comment]
测试了下确实是可以工作的

**Comment by sashimi-yzh** [comment]
好的, 谢谢啦

**Comment by junjie1475** [comment]
我研究了下发现配置文件的WindowHeight和WindowWidth 如果不是200/320 调用到SDL_SoftStretch的时候会因为src和dst的大小不一样触发 assert(0); 但是最迷的是上面的注释明明写了“APIs below are already implemented.”  我就是因为这个问题觉得可能是我配置文件写错了，因为我测试过我自己写的函数和原版SDL表现是一致的希望可以写到讲义里。
