### ISSUE TITLE
2019的PA 可以提供PDF Version 么

### ISSUE THREAD

**Issue by jiuxiaxixi** [NJU-ProjectN/ics-pa-gitbook#2]
# Generate a PDF file
$ gitbook pdf ./ ./mybook.pdf

# Generate an ePub file
$ gitbook epub ./ ./mybook.epub

# Generate a Mobi file
$ gitbook mobi ./ ./mybook.mobi

**Comment by sashimi-yzh** [comment]
有一些插件在PDF中显示不正常, 阅读效果不好, 所以暂时不提供PDF版本了.
