### ISSUE TITLE
关于内核栈和用户栈的分析描述

### ISSUE THREAD

**Issue by Rootphiv** [NJU-ProjectN/ics-pa-gitbook#21]
在4.4中，手册分析了``为什么目前不支持并发执行多个用户进程?``。然而我对其中的描述有些疑问。
手册中的大意如下：
> 1. 假设从用户进程A切换到用户进程B
> 2. 操作系统决定要调度用户进程B
> 3. CTE通过__am_switch()切换到B的虚拟地址空间
> 4. 当__am_switch()切换到B的虚拟地址空间之后，由于A的用户栈并不在B的虚拟地址空间里面，因此代码就不能再访问A的用户栈了

当从A进程切换到B进程时，``Context* __am_irq_handle(Context *c)``应该返回B进程的上下文地址``vaddr_b``，然而，这个虚拟地址是对于B进程的地址空间而言的。此时，系统仍运行在A进程的地址空间中；若``__am_switch(Context *c)``希望访问上下文地址``vaddr_b``，相当于拿着用户进程A的页表将``vaddr_b``翻译为某个A进程“拥有”的物理地址。
因此我认为此时系统无法读取B进程用户栈上的上下文，也无法读取其中``c->pdir``的内容，无法切换到B进程的地址空间。

所以我想这段分析是否应该修改为下面的意思：

为了方便描述, 我们假设某一时刻, 操作系统将要从用户进程A切换到用户进程B. 具体地, 在A运行的时候, 栈指针sp会指向A的用户栈. 当A执行系统调用, 或者中断到来的时候, 就会经过CTE陷入操作系统. 注意到这时CTE是在A的用户栈上保存A的上下文, 而sp也仍然指向A的用户栈. 这时, 操作系统决定要调度用户进程B, 它就会把B的上下文返回给CTE, CTE会依次进行如下操作:

* 通过__am_switch()切换到B的虚拟地址空间
* 在trap.S中恢复B的上下文

现在问题来了: **此时系统还运行在A的地址空间中，而B的用户栈并不在A的虚拟地址空间里面! **这意味着, 当__am_switch()收到B的上下文地址后，代码无法访问到其对应的正确物理地址. 于是__am_switch()无法正确地访问B的上下文，也无法从中得知B用户进程的地址空间描述符并切换到B的地址空间

**Comment by sashimi-yzh** [comment]
你的分析是对的, 在`__am_switch()`中访问`c`中的成员就已经开始出错了.

我重写了一下这段文字如下:
```
如果我们再仔细考虑过程中的细节, 就会发现其中的问题. 具体地, __am_switch()切换到B的虚拟地址空间之前, 需要先读出B的上下文结构中的地址空间描述符指针pdir(x86为cr3). 而B的上下文结构是上一次B进入CTE时在B的用户栈上创建的, 但B的用户栈并不在A的虚拟地址空间里面!

于是, 为了正确读出B的地址空间描述符指针, 我们需要先切换到B的虚拟地址空间; 但另一方面, 为了切换到B的虚拟地址空间, 我们需要先正确读出B的地址空间描述符指针! 这形成了一个"鸡和蛋"的循环依赖问题. 实际执行时, __am_switch()的代码将会读出一个错误的地址空间描述符指针, 从而无法正确切换到B的虚拟地址空间.
```

感谢指出这个问题!
