### ISSUE TITLE
Install Ubuntu部分的补充

### ISSUE THREAD

**Issue by dream-tentacle** [NJU-ProjectN/ics-pa-gitbook#23]
在该部分结尾有提示“不要使用Ubuntu的Software Updater”。不仅如此，在初次安装时也可能有**默认选中的选项**会导致自动更新：
![image](https://github.com/NJU-ProjectN/ics-pa-gitbook/assets/127286614/d74c7a01-323f-47dd-82b3-b30ca4dd12dd)

**Comment by sashimi-yzh** [comment]
已在讲义中补充, 感谢指出!

**Comment by dongth325** [comment]
什么意思。。、

**Comment by LynchTang** [comment]
> 什么意思。。、

看讲义比较好，这里的说法我也觉得语法上有问题，后半句不太好理解。

**Comment by dream-tentacle** [comment]
> 什么意思。。、



> > 什么意思。。、
> 
> 看讲义比较好，这里的说法我也觉得语法上有问题，后半句不太好理解。

哪里看不懂……这不是说得很清楚吗，在初次安装Ubuntu的时候，安装程序会默认选中Download updates while installing Ubuntu导致版本问题。

**Comment by LynchTang** [comment]
> > 什么意思。。、
> 
> > > 什么意思。。、
> > 
> > 
> > 看讲义比较好，这里的说法我也觉得语法上有问题，后半句不太好理解。
> 
> 哪里看不懂……这不是说得很清楚吗，在初次安装Ubuntu的时候，安装程序会默认选中Download updates while installing Ubuntu导致版本问题。

没什么。我的理解能力不够。

**Comment by QQJZ12138** [comment]
请问，我有用24.04.3版本，下载过程中没看到这个选项，是不是就不用注意这个问题了。

**Comment by LovenseChina** [comment]
这个22.04的终端，特别是vim很卡。
