### ISSUE TITLE
[Suggestions] PA3 NDL_GetTicks() 函数功能描述有错误/歧义

### ISSUE THREAD

**Issue by top-mind** [NJU-ProjectN/ics-pa-gitbook#25]
原文
```
// 以毫秒为单位返回系统时间
uint32_t NDL_GetTicks();
```
建议修改成
```
// 以毫秒为单位返回自 NDL 初始化时经过的时间
```
如果 NDL_GetTicks() 不从0开始，而是从 gettimeofday() 所指示的时间开始，PAL 在一些时间段运行会遇到莫名其妙的问题，疑似时间溢出了。

**Comment by sashimi-yzh** [comment]
用32位数据表示毫秒数, 应该足够40多天不会溢出. 你是在哪个ARCH下面遇到问题?

**Comment by top-mind** [comment]
native。
我的意思是用这种写法
```
uint32_t NDL_GetTicks() {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return ((uint32_t)tv.tv_sec) * 1000 + tv.tv_usec / 1000;
}
```
在 native 下每 46 天有 23 天正常, 23 天不正常。因为PAL的time用的是带符号的，只要时间到负数就会有问题。
当然照手册规定的写前23天不会有问题。我想是说讲义最好明确这个函数的行为。

**Comment by sashimi-yzh** [comment]
PAL调用的是`SDL_GetTicks()`, 它已经要求从0开始了. 也因为这样, 当时`NDL_GetTicks()`就故意设计成不必从0开始.

按道理即使`NDL_GetTicks()`不要求从0开始, PAL应该也不会出现native有23天不正常的问题?

**Comment by top-mind** [comment]
讲义：
```
SDL_GetTicks(): 它和NDL_GetTicks()的功能完全一样
```

**Comment by top-mind** [comment]
这么说讲义至少有一处有错误吧（

**Comment by sashimi-yzh** [comment]
你说得对, 我们修改一下, 感谢指出!

**Comment by sashimi-yzh** [comment]
已修改讲义中`SDL_GetTicks()`的描述
