### ISSUE TITLE
PA0 换源的问题

### ISSUE THREAD

**Issue by FurryAcetylCoA** [NJU-ProjectN/ics-pa-gitbook#33]
在讲义pa0.3中，换源的命令是这样的

```sh
bash -c 'echo "deb https://mirrors.bfsu.edu.cn/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list'
```

然而，这会禁用 security updates backports 这三个额外的 repositories

这导致apt只能获取到当前Ubuntu版本发行那一刻的软件列表和版本，后面所有更新都无法获取
而在安装期间，会有一次apt update/upgrade 。这就导致当去除其他三个repositories后，apt会觉
得当前系统里安装的软件比源里的新。
如果这个时候再尝试更新，就会出现下面这种场景：

![Picture](https://github.com/user-attachments/assets/eed3282a-d540-4ca0-b562-7648721f2fe5)

如果此时学员在网上搜索，并尝试使用aptitude降级，那么会导致重启后系统无法进入图形界面
这个问题在qq群几乎每周都会有人遇到。以至于5群专门有个群文件负责解释这件事

讲义似乎注意到了这件事， 并添加了以下内容

![Picture](https://github.com/user-attachments/assets/dd44ea2e-8204-4d48-a1fe-addc73b8dbec)

但由于这并不是源的问题，而是“缺少了必要的repositories”  因此这种方法并不能解决问题
总的来说，对于24.04 sources.list 至少需要包含以下四行内容

```
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-security main restricted universe multiverse
```

## 修改建议
使用sed进行查找/替换 换源
```sh
sed -i "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list
```

## 相关文档
https://help.ubuntu.com/community/Repositories

**Comment by sashimi-yzh** [comment]
已修复，感谢指出
