### ISSUE TITLE
PA0 与Windows的对比问题

### ISSUE THREAD

**Issue by FurryAcetylCoA** [NJU-ProjectN/ics-pa-gitbook#34]
在讲义pa0.5中，有这样一段内容

![Picture](https://github.com/user-attachments/assets/6bc724b2-c39c-4fa1-9fbb-4a260c66eb87)

实际上，在Windows下，也可以通过一行命令做到这件事，只需要以下PowerShell命令
（由我的好友，莫名出现的powershell选手 @CatMe0w 贡献）

```powershell
Get-ChildItem -Recurse -Include "*.c","*.h" | ForEach-Object { Get-Content $_ | Select-String "#include" } | Sort-Object | Get-Unique
```

这可以做为趣闻放在讲义上，以鼓励大家以后多探索不同的做事方法。

**Comment by sashimi-yzh** [comment]
原文想要表达的是windows GUI不方便做这件事，已修改原文。Windows PowerShell命令并没有作为讲义后续学习的对象，在此处提供具体PowerShell命令的意义不大，因此暂不添加该命令。
