### ISSUE TITLE
ics2020 PA4.4 抢占多任务描述不完整 

### ISSUE THREAD

**Issue by gitccl** [NJU-ProjectN/ics-pa-gitbook#4]
- 修改raise_intr()中的代码, 让处理器进入关中断状态:
  - x86 - 在保存EFLAGS寄存器后, 将其IF位置为0

后面应该还有一个：修改iret指令的实现, 将 EFLAGS 寄存器的 IF 位置为 1。
不知道是不是你们忘记写了还是你们故意这样设计的，如果是故意设置这样一个小坑当我没说😂😂。

**Comment by sashimi-yzh** [comment]
你好, 关于你提到如下描述:
```
修改iret指令的实现, 将 EFLAGS 寄存器的 IF 位置为 1
```
这个描述并不准确.

关于用户进程开中断的实现, 并不是通过iret直接实现的, 正确的实现方法讲义也已经描述清楚了, 如果你还不太明白, 可以再复习一下上下文切换相关的内容.

**Comment by gitccl** [comment]
好的好的，我当时没看仔细，谢谢你！
