### ISSUE TITLE
html网页本地跳转有问题

### ISSUE THREAD

**Issue by nuaalixu** [NJU-ProjectN/ics-pa-gitbook#5]
你好，网页本地阅读有两个小瑕疵：
1.本地阅读时，不支持当前标签页跳转，需要<在新标签页中打开链接>；(theme.js可修改)
2.通过点击Introduction超链接无法正确跳转到index.html文件。(data-path="./"和href="./")

**Comment by sashimi-yzh** [comment]
你好, 这些html是gitbook自动生成的, 你知道应该如何修改html才能修复这两个问题吗? @nuaalixu

**Comment by nuaalixu** [comment]
> 你好, 这些html是gitbook自动生成的, 你知道应该如何修改html才能修复这两个问题吗? @nuaalixu

你好。
1.首先第一个本地跳转的问题，我将gitbook/theme.js中的字段
```js
 if(m)for(n.handler&&
```
替换成
```js
for(false)for(n.handler&&
```
注意我没有测试是否对线上阅读有影响。
2.点击Introduction正确跳转到index.html文件的问题。我将每个*.html文件中的
```html
        <li class="chapter " data-level="1.1" data-path="./">
            
                <a href="./">
            
                    
                    Introduction
            
                </a>
```
替换成
        <li class="chapter " data-level="1.1" data-path="index.html">
            
                <a href="index.html">
            
                    
                    Introduction
            
                </a>

**Comment by sashimi-yzh** [comment]
感谢指导! 我试了一下, 在线和离线应该都没问题了.

另外
> ```js
> for(false)for(n.handler&&
> ```
这里应该是
```js
if(false)for(n.handler&&
```

**Comment by nuaalixu** [comment]
> 感谢指导! 我试了一下, 在线和离线应该都没问题了.
> 
> 另外
> 
> > ```js
> > for(false)for(n.handler&&
> > ```
> 
> 这里应该是
> 
> ```js
> if(false)for(n.handler&&
> ```

不客气，是的。我打错字了。
