### ISSUE TITLE
关于包括Noop的完整ProjectN

### ISSUE THREAD

**Issue by BobBogart** [NJU-ProjectN/ics-pa-gitbook#7]
您好！请问含有Noop的完整ProjectN，或者只有Noop的类似pa的讲义哪里有呀？

**Comment by sashimi-yzh** [comment]
你好, 目前noop还没有讲义.

**Comment by sashimi-yzh** [comment]
我现在跑去维护[一生一芯](https://ysyx.oscc.cc/)了, 估计不会单独出NOOP的讲义了, 如果你对处理器设计感兴趣, 可以参考一生一芯的讲义.
