### ISSUE TITLE
Is there a plan to migrate to cmake?

### ISSUE THREAD

**Issue by LanceGe** [NJU-ProjectN/ics-pa-gitbook#8]
Though the Makefile's work smoothly in this project, I think it might be a good idea to migrate to `cmake`. `cmake` is widely used in modern software development, and if the students can learn how to use it in this course project then they will get better prepared for industry.

**Comment by jiangyy** [comment]
Nope. We intentionally chose GNU's Make to make every low-level detail visible to students.
